export const SYMBOL_TYPE_MAP = {
    'Symbols Type': 'Royals',
    __EMPTY_17: 'Suits',
    __EMPTY_18: 'Other',
    __EMPTY_19: 'Gold Bar',
    __EMPTY_20: 'Fruits',
    __EMPTY_21: 'Gems',
};

export const FEATURES_MAP = {
    Features: 'Free Spins',
    __EMPTY_67: 'Expanding Wilds',
    __EMPTY_68: 'Stacked Wilds',
    __EMPTY_69: 'Sticky Wilds',
    __EMPTY_70: 'Other Wilds',
    __EMPTY_71: 'Scatter Wilds/Symbols',
    __EMPTY_72: 'Mystery Symbols',
    __EMPTY_73: 'Respins',
    __EMPTY_74: 'Buy a bonus',
    __EMPTY_75: 'Multipliers (With or without wilds)',
    __EMPTY_76: 'Bonus Game',
    __EMPTY_77: 'Gamble',
    __EMPTY_78: 'Hold and Win',
    __EMPTY_79: 'Trail',
    __EMPTY_80: 'Cascading Reels',
    __EMPTY_81: 'Pick Me',
    __EMPTY_82: 'Cash Collect',
};

export const THEMES_MAP = {
    Themes: 'Nature',
    __EMPTY_22: 'Magic',
    __EMPTY_23: 'Branded',
    __EMPTY_24: 'Fruit',
    __EMPTY_25: 'Egypt',
    __EMPTY_26: 'Gems',
    __EMPTY_27: 'Irish',
    __EMPTY_28: 'Fishing',
    __EMPTY_29: 'Other',
    __EMPTY_30: 'Water',
    __EMPTY_31: 'Asian',
    __EMPTY_32: 'Money',
    __EMPTY_33: 'Jungle',
    __EMPTY_34: 'Christmas',
    __EMPTY_35: 'Mining',
    __EMPTY_36: 'Fairy Tale',
    __EMPTY_37: 'Wild West',
    __EMPTY_38: 'Fantasy',
    __EMPTY_39: 'Mayan/Aztec',
    __EMPTY_40: 'Space',
    __EMPTY_41: 'Pirate',
    __EMPTY_42: 'Winter',
    __EMPTY_43: 'Detective',
    __EMPTY_44: 'Dinosaurs',
    __EMPTY_45: 'Vikings',
    __EMPTY_46: 'Farm',
    __EMPTY_47: 'Sweets',
    __EMPTY_48: 'Bubble',
    __EMPTY_49: 'Mexico',
    __EMPTY_50: 'Sports',
    __EMPTY_51: 'Tomb Raider',
    __EMPTY_52: 'Retro',
    __EMPTY_53: 'Elements',
    __EMPTY_54: 'Medieval',
    __EMPTY_55: 'Gods',
    __EMPTY_56: 'Fire',
    __EMPTY_57: 'Horror',
    __EMPTY_58: 'Bank',
    __EMPTY_59: 'Robbery',
    __EMPTY_60: 'Greece',
    __EMPTY_61: 'Island',
    __EMPTY_62: 'Atlantis',
    __EMPTY_63: 'Music',
    __EMPTY_64: 'Arabic',
    __EMPTY_65: 'Rome',
};
