const includedGames = [
	'bingo-bingote [botemania]',
	'bingo-bingote [canalbingo]',
	'bingo-bingote-desktop [botemania]',
	'bingo-bingote-desktop [canalbingo]',
	'bingo-rapi [botemania]',
	'bingo-rapi [canalbingo]',
	'bingo-rapi-desktop [botemania]',
	'bingo-rapi-desktop [canalbingo]',
	'bingo-superbingo [botemania]',
	'bingo-superbingo [canalbingo]',
	'bingo-superbingo-desktop [botemania]',
	'bingo-superbingo-desktop [canalbingo]',
	'bingo-tiki-botemania [botemania]',
	'bingo-tiki-botemania-desktop [botemania]',
	'bingo-tiki-canalbingo [botemania]',
	'bingo-tiki-canalbingo-desktop [botemania]',
	'play-80-ball-bingo [botemania]',
	'play-80-ball-bingo [canalbingo]',
	'play-80-ball-bingo [monopolycasinospain]',
	'play-80-ball-bingo-link-spain [botemania]',
	'play-80-ball-bingo-link-spain [canalbingo]',
	'play-80-ball-bingo-link-spain [monopolycasinospain]',
	'play-bingo-tiki [botemania]',
	'play-bingo-tiki [canalbingo]',
	'play-bingo-tiki [monopolycasinospain]',
	'play-bingote [botemania]',
	'play-bingote [canalbingo]',
	'play-bingote [monopolycasinospain]',
	'play-bingote-link-spain [botemania]',
	'play-bingote-link-spain [canalbingo]',
	'play-bingote-link-spain [monopolycasinospain]',
	'play-rapi-bingo [canalbingo]',
	'play-rapi-bingo [botemania]',
	'play-rapi-bingo [monopolycasinospain]',
	'play-rapi-bingo-link-spain [botemania]',
	'play-rapi-bingo-link-spain [canalbingo]',
	'play-rapi-bingo-link-spain [monopolycasinospain]',
	'play-session-bingo [botemania]',
	'play-session-bingo [canalbingo]',
	'play-session-bingo [monopolycasinospain]',
	'play-session-bingo-link-spain [botemania]',
	'play-session-bingo-link-spain [canalbingo]',
	'play-session-bingo-link-spain [monopolycasinospain]',
	'play-super-bingo [botemania]',
	'play-super-bingo [monopolycasinospain]',
	'play-super-bingo [canalbingo]',
	'play-super-bingo-link-spain [botemania]',
	'play-super-bingo-link-spain [canalbingo]',
	'play-super-bingo-link-spain [monopolycasinospain]',
	'play-tiki-bingo-link-spain [botemania]',
	'play-tiki-bingo-link-spain [canalbingo]',
	'play-tiki-bingo-link-spain [monopolycasinospain]'
];

module.exports = {
	includedGames
}
