const includedGames = [
	'play-ev-autoroulette [botemania]',
	'play-ev-autoroulette [monopolycasinospain]',
	'play-ev-bola-rapida-en-vivo [botemania]',
	'play-ev-bola-rapida-en-vivo [monopolycasinospain]',
	'play-ev-casino-holdem [monopolycasinospain]',
	'play-ev-first-person-american-roulette [botemania]',
	'play-ev-first-person-american-roulette [monopolycasinospain]',
	'play-ev-first-person-auto-lightning-roulette [botemania]',
	'play-ev-first-person-auto-lightning-roulette [monopolycasinospain]',
	'play-ev-first-person-auto-lightning-roulette-es [botemania]',
	'play-ev-first-person-auto-lightning-roulette-es [monopolycasinospain]',
	'play-ev-first-person-blackjack [botemania]',
	'play-ev-first-person-deal-or-no-deal [botemania]',
	'play-ev-first-person-deal-or-no-deal [monopolycasinospain]',
	'play-ev-first-person-lightning-roulette [botemania]',
	'play-ev-first-person-lightning-roulette [monopolycasinospain]',
	'play-ev-first-person-roulette [botemania]',
	'play-ev-first-person-roulette [monopolycasinospain]',
	'play-ev-gonzos-treasure-hunt [botemania]',
	'play-ev-gonzos-treasure-hunt [monopolycasinospain]',
	'play-ev-lightning-roulette [botemania]',
	'play-ev-lightning-roulette [monopolycasinospain]',
	'play-ev-roulette [botemania]',
	'play-ev-roulette [monopolycasinospain]',
	'play-ev-roulette-live [botemania]',
	'play-ev-roulette-live [monopolycasinospain]',
	'play-ev-ruleta-automatica-french [botemania]',
	'play-ev-ruleta-automatica-french [monopolycasinospain]',
	'play-ev-ruleta-dual-play [botemania]',
	'play-ev-ruleta-dual-play [monopolycasinospain]',
	'play-ev-ruleta-en-vivo [botemania]',
	'play-ev-ruleta-en-vivo [monopolycasinospain]',
	'play-ev-ruleta-relampago-en-vivo [botemania]',
	'play-ev-ruleta-relampago-en-vivo [monopolycasinospain]',
	'play-ev-speed-roulette [botemania]',
	'play-ev-speed-vip-blackjack-d [botemania]',
	'play-ev-xxxtreme-first-person-lightning-roulette [botemania]',
	'play-ev-xxxtreme-first-person-lightning-roulette [monopolycasinospain]',
	'play-evo-american-roulette [botemania]',
	'play-evo-american-roulette [monopolycasinospain]',
	'play-evo-casino-holdem [botemania]',
	'play-evo-casino-holdem [monopolycasinospain]',
	'play-ev-first-person-blackjack [monopolycasinospain]',
	'play-ev-fp-dream-catcher [botemania]',
	'play-ev-fp-dream-catcher [monopolycasinospain]',
	'play-ev-ruleta-automatica [botemania]',
	'play-ev-ruleta-automatica [monopolycasinospain]'
];

module.exports = {
	includedGames
}
