const includedGames = [
	'play-9k-yeti [botemania]',
	'play-9k-yeti [canalbingo]',
	'play-elf-slingo [botemania]',
	'play-elf-slingo [canalbingo]',
	'play-gmr-slingo-rakin-bacon [botemania]',
	'play-gmr-slingo-rakin-bacon [canalbingo]',
	'play-slingo-advance [botemania]',
	'play-slingo-advance [canalbingo]',
	'play-slingo-berserk [botemania]',
	'play-slingo-berserk [canalbingo]',
	'play-slingo-big-wheel [botemania]',
	'play-slingo-big-wheel [canalbingo]',
	'play-slingo-book-of-slingo [botemania]',
	'play-slingo-book-of-slingo [canalbingo]',
	'play-slingo-centurion [botemania]',
	'play-slingo-centurion [canalbingo]',
	'play-slingo-cleopatra [botemania]',
	'play-slingo-cleopatra [canalbingo]',
	'play-slingo-da-vinci-diamonds  [canalbingo]',
	'play-slingo-da-vinci-diamonds [botemania]',
	'play-slingo-extreme [botemania]',
	'play-slingo-extreme [canalbingo]',
	'play-slingo-fire-and-ice [botemania]',
	'play-slingo-fire-and-ice [canalbingo]',
	'play-slingo-fishin [botemania]',
	'play-slingo-fishin [canalbingo]',
	'play-slingo-fluffy-favourites [botemania]',
	'play-slingo-fluffy-favourites [canalbingo]',
	'play-slingo-fortunes [botemania]',
	'play-slingo-fortunes [canalbingo]',
	'play-slingo-lightning [botemania]',
	'play-slingo-lightning [canalbingo]',
	'play-slingo-lobstermania [botemania]',
	'play-slingo-lobstermania [canalbingo]',
	'play-slingo-lucky-joker [botemania]',
	'play-slingo-lucky-joker [canalbingo]',
	'play-slingo-pirate-treasure [botemania]',
	'play-slingo-pirate-treasure [canalbingo]',
	'play-slingo-racing [botemania]',
	'play-slingo-racing [canalbingo]',
	'play-slingo-rainbow-riches [botemania]',
	'play-slingo-rainbow-riches [canalbingo]',
	'play-slingo-red-hot-slingo [botemania]',
	'play-slingo-red-hot-slingo [canalbingo]',
	'play-slingo-reel-king [botemania]',
	'play-slingo-reel-king [canalbingo]',
	'play-slingo-space-invaders [botemania]',
	'play-slingo-space-invaders [canalbingo]',
	'play-slingo-starburst [botemania]',
	'play-slingo-starburst [canalbingo]',
	'play-slingo-stinkin-rich [botemania]',
	'play-slingo-stinkin-rich [canalbingo]',
	'play-slingo-sweet-bonanza [botemania]',
	'play-slingo-sweet-bonanza [canalbingo]',
	'play-slingo-tetris [botemania]',
	'play-slingo-tetris [canalbingo]',
	'play-slingo-wolf-snowstorm [botemania]',
	'play-slingo-wolf-snowstorm [canalbingo]',
	'play-slingo-xxxtreme [botemania]',
	'play-slingo-xxxtreme [canalbingo]'
];

module.exports = {
	includedGames
}
