const includedGames = [
	'GMR_4_FANTASTIC_FISH_engage',
	'GMR_9K_YETI_engage',
	'GMR_BLACKJACK_XCHANGE_engage',
	'GMR_BOOK_OF_SLINGO',
	'GMR_RED_HOT_SLINGO_engage',
	'GMR_SLINGO_ADVANCE_engage',
	'GMR_SLINGO_BERSERK',
	'GMR_SLINGO_BIG_WHEEL_engage',
	'GMR_SLINGO_CENTURION_engage',
	'GMR_SLINGO_DAVINCI_DIAMONDS_engage',
	'GMR_SLINGO_EXTREME_engage',
	'GMR_SLINGO_FISHIN_FRENZY_engage',
	'GMR_SLINGO_FLUFFYFAVOURITES_engage',
	'GMR_SLINGO_FORTUNES',
	'GMR_SLINGO_LIGHTNING',
	'GMR_SLINGO_LUCKY_JOKER',
	'GMR_SLINGO_LUCKY_LARRYS_LOBSTERMANIA_SLINGO_engage',
	'GMR_SLINGO_MONEY_TRAIN_engage',
	'GMR_SLINGO_PIRATE_TREASURE_engage',
	'GMR_SLINGO_RACING_engage',
	'GMR_SLINGO_RAKIN_BACON',
	'GMR_SLINGO_REEL_KING_engage',
	'GMR_SLINGO_SPACE_INVADERS_engage',
	'GMR_SLINGO_STARBURST_engage',
	'GMR_SLINGO_STINKIN_RICH_engage',
	'GMR_SLINGO_SWEET_BONANZA_engage',
	'GMR_SLINGO_TETRIS_engage',
	'GMR_SLINGO_WOLF_SNOWSTORM_engage',
	'GMR_SLINGO_XXXTREME_engage'	
];

module.exports = {
	includedGames
}
