const includedGames = [
	'play-igt-100000-pyramid [ballyuk] ',
	'play-igt-100000-pyramid [doublebubblebingo] ',
	'play-igt-100000-pyramid [jackpotjoy] ',
	'play-igt-100000-pyramid [monopolycasino]',
	'play-igt-100000-pyramid [virgingames]',
	'play-igt-bill-and-ted [ballyuk]',
	'play-igt-bill-and-ted [doublebubblebingo]',
	'play-igt-bill-and-ted [jackpotjoy]',
	'play-igt-bill-and-ted [monopolycasino]',
	'play-igt-bill-and-ted [virgingames]',
	'play-igt-blackjack-poker-and-paris [ballyuk]',
	'play-igt-blackjack-poker-and-paris [doublebubblebingo]',
	'play-igt-bounty-o-bucks [ballyuk]',
	'play-igt-bounty-o-bucks [doublebubblebingo]',
	'play-igt-bounty-o-bucks [jackpotjoy]',
	'play-igt-bounty-o-bucks [monopolycasino]',
	'play-igt-bounty-o-bucks [rainbowriches]',
	'play-igt-bounty-o-bucks [virgingames]',
	'play-igt-cash-eruption-red-hot-joker [ballyuk]',
	'play-igt-cash-eruption-red-hot-joker [doublebubblebingo]',
	'play-igt-cash-eruption-red-hot-joker [jackpotjoy]',
	'play-igt-cash-eruption-red-hot-joker [monopolycasino]',
	'play-igt-cash-eruption-red-hot-joker [rainbowriches]',
	'play-igt-cash-eruption-red-hot-joker [virgingames]',
	'play-igt-cash-melon [ballyuk]',
	'play-igt-cash-melon [doublebubblebingo]',
	'play-igt-cash-melon [jackpotjoy]',
	'play-igt-cash-melon [monopolycasino]',
	'play-igt-cash-melon [rainbowriches]',
	'play-igt-cash-melon [virgingames]',
	'play-igt-cats [doublebubblebingo] ',
	'play-igt-cats [jackpotjoy] ',
	'play-igt-cats [monopolycasino] ',
	'play-igt-cats [virgingames] ',
	'play-igt-cleopatra [doublebubblebingo] ',
	'play-igt-cleopatra-gold [ballyuk]',
	'play-igt-cleopatra-gold [doublebubblebingo] ',
	'play-igt-cleopatra-gold [jackpotjoy]',
	'play-igt-cleopatra-gold [monopolycasino]',
	'play-igt-cleopatra-gold [rainbowriches]',
	'play-igt-cleopatra-gold [virgingames]',
	'play-igt-cleopatra-grand [ballyuk]',
	'play-igt-cleopatra-grand [doublebubblebingo]',
	'play-igt-cleopatra-grand [jackpotjoy]',
	'play-igt-cleopatra-grand [monopolycasino]',
	'play-igt-cleopatra-grand [rainbowriches]',
	'play-igt-cleopatra-grand [virgingames]',
	'play-igt-cleopatra-hyper-hits [ballyuk]',
	'play-igt-cleopatra-hyper-hits [doublebubblebingo]',
	'play-igt-cleopatra-hyper-hits [jackpotjoy]',
	'play-igt-cleopatra-hyper-hits [monopolycasino]',
	'play-igt-cleopatra-hyper-hits [rainbowriches]',
	'play-igt-cleopatra-hyper-hits [virgingames]',
	'play-igt-cleopatra-ii [ballyuk]',
	'play-igt-cleopatra-ii [doublebubblebingo]',
	'play-igt-cleopatra-ii [jackpotjoy]',
	'play-igt-cleopatra-ii [monopolycasino]',
	'play-igt-cleopatra-ii [rainbowriches]',
	'play-igt-cleopatra-ii [virgingames]',
	'play-igt-cleopatra-megaways [ballyuk]',
	'play-igt-cleopatra-megaways [doublebubblebingo]',
	'play-igt-cleopatra-megaways [jackpotjoy]',
	'play-igt-cleopatra-megaways [monopolycasino]',
	'play-igt-cleopatra-megaways [rainbowriches]',
	'play-igt-cleopatra-megaways [virgingames]',
	'play-igt-cleopatra-plus [ballyuk]',
	'play-igt-cleopatra-plus [doublebubblebingo] ',
	'play-igt-cleopatra-plus [jackpotjoy]',
	'play-igt-cleopatra-plus [monopolycasino]',
	'play-igt-cleopatra-plus [virgingames]',
	'play-igt-coin-o-mania [ballyuk]',
	'play-igt-coin-o-mania [doublebubblebingo] ',
	'play-igt-coin-o-mania [jackpotjoy]',
	'play-igt-coin-o-mania [monopolycasino]',
	'play-igt-coin-o-mania [virgingames]',
	'play-igt-cool-catch [ballyuk]',
	'play-igt-cool-catch [doublebubblebingo]',
	'play-igt-cool-catch [jackpotjoy]',
	'play-igt-cool-catch [monopolycasino]',
	'play-igt-cool-catch [rainbowriches]',
	'play-igt-cool-catch [virgingames]',
	'play-igt-da-vinci-diamonds [ballyuk]',
	'play-igt-da-vinci-diamonds [doublebubblebingo]',
	'play-igt-da-vinci-diamonds [monopolycasino]',
	'play-igt-da-vinci-diamonds [rainbowriches]',
	'play-igt-da-vinci-diamonds [virgingames]',
	'play-igt-da-vinci-dual-play [ballyuk]',
	'play-igt-da-vinci-dual-play [monopolycasino] ',
	'play-igt-da-vinci-dual-play [virgingames]',
	'play-igt-double-diamond [ballyuk]',
	'play-igt-elephant-king [ballyuk]',
	'play-igt-elephant-king [doublebubblebingo] ',
	'play-igt-elephant-king [jackpotjoy]',
	'play-igt-elephant-king [monopolycasino]',
	'play-igt-elephant-king [virgingames]',
	'play-igt-fortune-coin-boost-classic [ballyuk]',
	'play-igt-fortune-coin-boost-classic [doublebubblebingo]',
	'play-igt-fortune-coin-boost-classic [jackpotjoy]',
	'play-igt-fortune-coin-boost-classic [monopolycasino]',
	'play-igt-fortune-coin-boost-classic [rainbowriches]',
	'play-igt-fortune-coin-boost-classic [virgingames]',
	'play-igt-ghostbusters-plus [doublebubblebingo] ',
	'play-igt-ghostbusters-plus [jackpotjoy]',
	'play-igt-ghostbusters-plus [monopolycasino]',
	'play-igt-ghostbusters-plus [virgingames]',
	'play-igt-golden-goddess [ballyuk] ',
	'play-igt-golden-goddess [doublebubblebingo] ',
	'play-igt-golden-goddess [jackpotjoy] ',
	'play-igt-golden-goddess [monopolycasino] ',
	'play-igt-golden-goddess [virgingames] ',
	'play-igt-great-bear [ballyuk]',
	'play-igt-great-bear [doublebubblebingo]',
	'play-igt-great-bear [jackpotjoy]',
	'play-igt-great-bear [monopolycasino]',
	'play-igt-great-bear [rainbowriches]',
	'play-igt-great-bear [virgingames]',
	'play-igt-icy-wilds [doublebubblebingo] ',
	'play-igt-icy-wilds [jackpotjoy] ',
	'play-igt-icy-wilds [monopolycasino] ',
	'play-igt-icy-wilds [virgingames] ',
	'play-igt-its-magic [doublebubblebingo] ',
	'play-igt-its-magic [jackpotjoy] ',
	'play-igt-its-magic [monopolycasino] ',
	'play-igt-its-magic [virgingames] ',
	'play-igt-kitty-glitter [ballyuk]',
	'play-igt-kitty-glitter [doublebubblebingo]',
	'play-igt-kitty-glitter [jackpotjoy]',
	'play-igt-kitty-glitter [monopolycasino]',
	'play-igt-kitty-glitter [virgingames]',
	'play-igt-magic-of-the-nile [ballyuk]',
	'play-igt-magic-of-the-nile [doublebubblebingo]',
	'play-igt-magic-of-the-nile [jackpotjoy]',
	'play-igt-magic-of-the-nile [monopolycasino]',
	'play-igt-magic-of-the-nile [virgingames]',
	'play-igt-medusa-queen-of-stone [ballyuk]',
	'play-igt-medusa-queen-of-stone [doublebubblebingo]',
	'play-igt-medusa-queen-of-stone [jackpotjoy]',
	'play-igt-medusa-queen-of-stone [monopolycasino]',
	'play-igt-medusa-queen-of-stone [rainbowriches]',
	'play-igt-medusa-queen-of-stone [virgingames]',
	'play-igt-mistress-of-egypt [ballyuk]',
	'play-igt-mistress-of-egypt [doublebubblebingo]',
	'play-igt-mistress-of-egypt [jackpotjoy]',
	'play-igt-mistress-of-egypt [monopolycasino]',
	'play-igt-mistress-of-egypt [rainbowriches]',
	'play-igt-mistress-of-egypt [virgingames]',
	'play-igt-pharaohs-fortune [ballyuk]',
	'play-igt-pharaohs-fortune [doublebubblebingo]',
	'play-igt-pharaohs-fortune [jackpotjoy]',
	'play-igt-pharaohs-fortune [monopolycasino]',
	'play-igt-pharaohs-fortune [rainbowriches]',
	'play-igt-pharaohs-fortune [virgingames]',
	'play-igt-pixies-of-the-forest [ballyuk]',
	'play-igt-pixies-of-the-forest [doublebubblebingo] ',
	'play-igt-pixies-of-the-forest [jackpotjoy] ',
	'play-igt-pixies-of-the-forest [monopolycasino] ',
	'play-igt-pixies-of-the-forest [rainbowriches] ',
	'play-igt-pixies-of-the-forest [virgingames] ',
	'play-igt-pixies-of-the-forest-2 [ballyuk] ',
	'play-igt-pixies-of-the-forest-2 [doublebubblebingo] ',
	'play-igt-pixies-of-the-forest-2 [jackpotjoy] ',
	'play-igt-pixies-of-the-forest-2 [monopolycasino] ',
	'play-igt-pixies-of-the-forest-2 [virgingames] ',
	'play-igt-roulette [virgingames]',
	'play-igt-scarab [doublebubblebingo] ',
	'play-igt-scarab [jackpotjoy] ',
	'play-igt-scarab [monopolycasino] ',
	'play-igt-scarab [virgingames] ',
	'play-igt-shes-a-rich-girl [doublebubblebingo] ',
	'play-igt-shes-a-rich-girl [virgingames]',
	'play-igt-siberian-storm [ballyuk] ',
	'play-igt-siberian-storm [doublebubblebingo] ',
	'play-igt-siberian-storm [jackpotjoy] ',
	'play-igt-siberian-storm [monopolycasino] ',
	'play-igt-siberian-storm [virgingames] ',
	'play-igt-skeleton-key [ballyuk]',
	'play-igt-skeleton-key [doublebubblebingo]',
	'play-igt-skeleton-key [jackpotjoy]',
	'play-igt-skeleton-key [monopolycasino]',
	'play-igt-skeleton-key [virgingames]',
	'play-igt-stinkin-rich-skunks-gone-wild [ballyuk]',
	'play-igt-stinkin-rich-skunks-gone-wild [doublebubblebingo]',
	'play-igt-stinkin-rich-skunks-gone-wild [jackpotjoy]',
	'play-igt-stinkin-rich-skunks-gone-wild [monopolycasino]',
	'play-igt-stinkin-rich-skunks-gone-wild [rainbowriches]',
	'play-igt-stinkin-rich-skunks-gone-wild [virgingames]',
	'play-igt-treasure-box-dynasty [ballyuk]',
	'play-igt-treasure-box-dynasty [doublebubblebingo]',
	'play-igt-treasure-box-dynasty [jackpotjoy]',
	'play-igt-treasure-box-dynasty [monopolycasino]',
	'play-igt-treasure-box-dynasty [rainbowriches]',
	'play-igt-treasure-box-dynasty [virgingames]',
	'play-igt-treasures-of-the-pyramid [ballyuk]',
	'play-igt-treasures-of-the-pyramid [doublebubblebingo]',
	'play-igt-treasures-of-the-pyramid [jackpotjoy]',
	'play-igt-treasures-of-the-pyramid [monopolycasino]',
	'play-igt-treasures-of-the-pyramid [rainbowriches]',
	'play-igt-treasures-of-the-pyramid [virgingames]',
	'play-igt-treasures-of-troy [doublebubblebingo] ',
	'play-igt-treasures-of-troy [virgingames] ',
	'play-igt-vegas-cash-eruption [ballyuk]',
	'play-igt-vegas-cash-eruption [doublebubblebingo]',
	'play-igt-vegas-cash-eruption [jackpotjoy]',
	'play-igt-vegas-cash-eruption [monopolycasino]',
	'play-igt-vegas-cash-eruption [rainbowriches]',
	'play-igt-vegas-cash-eruption [virgingames]',
	'play-igt-wheel-of-fortune-elegant-emeralds [ballyuk]',
	'play-igt-wheel-of-fortune-elegant-emeralds [doublebubblebingo]',
	'play-igt-wheel-of-fortune-elegant-emeralds [jackpotjoy]',
	'play-igt-wheel-of-fortune-elegant-emeralds [monopolycasino]',
	'play-igt-wheel-of-fortune-elegant-emeralds [rainbowriches]',
	'play-igt-wheel-of-fortune-elegant-emeralds [virgingames]',
	'play-igt-wheel-of-fortune-megaways [ballyuk]',
	'play-igt-wheel-of-fortune-megaways [doublebubblebingo]',
	'play-igt-wheel-of-fortune-megaways [jackpotjoy]',
	'play-igt-wheel-of-fortune-megaways [monopolycasino]',
	'play-igt-wheel-of-fortune-megaways [rainbowriches]',
	'play-igt-wheel-of-fortune-megaways [virgingames]',
	'play-igt-wheel-of-fortune-ruby-riches [ballyuk]',
	'play-igt-wheel-of-fortune-ruby-riches [doublebubblebingo]',
	'play-igt-wheel-of-fortune-ruby-riches [jackpotjoy]',
	'play-igt-wheel-of-fortune-ruby-riches [monopolycasino]',
	'play-igt-wheel-of-fortune-ruby-riches [rainbowriches]',
	'play-igt-wheel-of-fortune-ruby-riches [virgingames]',
	'play-igt-wild-fury [ballyuk] ',
	'play-igt-wild-fury [doublebubblebingo] ',
	'play-igt-wild-fury [jackpotjoy] ',
	'play-igt-wild-fury [monopolycasino] ',
	'play-igt-wild-fury [virgingames] ',
	'play-igt-wolf-run [doublebubblebingo] ',
	'play-igt-wolf-run [jackpotjoy] ',
	'play-igt-wolf-run [monopolycasino] ',
	'play-igt-wolf-run [virgingames] ',
	'play-igt-wolf-run-eclipse [ballyuk]',
	'play-igt-wolf-run-eclipse [doublebubblebingo]',
	'play-igt-wolf-run-eclipse [jackpotjoy]',
	'play-igt-wolf-run-eclipse [monopolycasino]',
	'play-igt-wolf-run-eclipse [rainbowriches]',
	'play-igt-wolf-run-eclipse [virgingames]',
	'play-igt-cash-eruption [ballyuk]',
	'play-igt-cash-eruption [doublebubblebingo]',
	'play-igt-cash-eruption [jackpotjoy]',
	'play-igt-cash-eruption [monopolycasino]',
	'play-igt-cash-eruption [rainbowriches]',
	'play-igt-cash-eruption [virgingames]',
	'play-igt-cleopatra [ballyuk] ',
	'play-igt-cleopatra [jackpotjoy] ',
	'play-igt-cleopatra [monopolycasino] ',
	'play-igt-cleopatra [rainbowriches]',
	'play-igt-cleopatra [virgingames] ',
	'play-igt-da-vinci-diamonds [jackpotjoy] '
];

module.exports = {
	includedGames
}
