const includedGames = [
	'play-asl-dreamy-genie [botemania]',
	'play-asl-dreamy-genie [canalbingo]',
	'play-asl-egyptian-magic [botemania]',
	'play-asl-egyptian-magic [canalbingo]',
	'play-gam-books-and-bulls [botemania]',
	'play-gam-books-and-bulls [canalbingo]',
	'play-gam-books-and-bulls-m [botemania]',
	'play-gam-books-and-bulls-m [canalbingo]',
	'play-gam-books-and-temples [botemania]',
	'play-gam-books-and-temples [canalbingo]',
	'play-gam-books-and-temples-m [botemania]',
	'play-gam-books-and-temples-m [canalbingo]',
	'play-gam-fancy-fruits [botemania]',
	'play-gam-fancy-fruits [canalbingo]',
	'play-gam-fancy-fruits-m [botemania]',
	'play-gam-fancy-fruits-m [canalbingo]',
	'play-gam-la-dolce-vita [botemania]',
	'play-gam-la-dolce-vita [canalbingo]',
	'play-gam-la-dolce-vita-golden-nights [botemania]',
	'play-gam-la-dolce-vita-golden-nights-m [botemania]',
	'play-gam-la-dolce-vita-m [botemania]',
	'play-gam-la-dolce-vita-m [canalbingo]',
	'play-gam-the-book-beyond [botemania]',
	'play-gam-the-book-beyond [canalbingo]',
	'play-gam-the-book-beyond-m [botemania]',
	'play-gam-the-book-beyond-m [canalbingo]',
	'play-ory-fancy-fruits [botemania]',
	'play-ory-fancy-fruits [canalbingo]',
	'play-ory-fancy-fruits-m [botemania]',
	'play-ory-fancy-fruits-m [canalbingo]',
	'play-ory-fruit-twist [botemania]',
	'play-ory-fruit-twist [canalbingo]',
	'play-ory-fruit-twist-m [botemania]',
	'play-ory-fruit-twist-m [canalbingo]',
	'play-ory-golden-7-classic [botemania]',
	'play-ory-golden-7-classic [canalbingo]',
	'play-ory-golden-7-classic-m [botemania]',
	'play-ory-golden-7-classic-m [canalbingo]',
	'play-ory-sceptre-of-cleo [botemania]',
	'play-ory-sceptre-of-cleo [canalbingo]',
	'play-ory-sceptre-of-cleo-m [botemania]',
	'play-ory-sceptre-of-cleo-m [canalbingo]',
	'play-ory-the-book-beyond [botemania]',
	'play-ory-the-book-beyond [canalbingo]',
	'play-ory-the-book-beyond-m [botemania]',
	'play-ory-the-book-beyond-m [canalbingo]',
	'play-phoenix-fury [botemania]',
	'play-phoenix-fury [canalbingo]',
	'play-asl-diamond-safari [botemania]',
	'play-asl-diamond-safari [canalbingo]',
	'play-ory-crystal-ball [botemania]',
	'play-ory-crystal-ball [canalbingo]',
	'play-ory-crystal-ball-m [botemania]',
	'play-ory-crystal-ball-m [canalbingo]',
	'play-ory-wild-dolphins [botemania] ',
	'play-ory-wild-dolphins [canalbingo] ',
	'play-ory-wild-dolphins-m [botemania]',
	'play-ory-wild-dolphins-m [canalbingo]'
];

module.exports = {
	includedGames
}
