const includedGames = [
    'play-stl-american-blackjack [ballyuk]',
    'play-stl-american-blackjack [doublebubblebingo]',
    'play-stl-american-blackjack [jackpotjoy]',
    'play-stl-american-blackjack [monopolycasino]',
    'play-stl-american-blackjack [rainbowriches]',
    'play-stl-american-blackjack [virgingames]',
    'play-stl-auto-roulette [ballyuk]',
    'play-stl-auto-roulette [doublebubblebingo]',
    'play-stl-auto-roulette [jackpotjoy]',
    'play-stl-auto-roulette [monopolycasino]',
    'play-stl-auto-roulette [rainbowriches]',
    'play-stl-auto-roulette [virgingames]',
	'play-stl-ballys-roulette [ballyuk]',
	'play-stl-blackjack-allure [ballyuk]',
	'play-stl-blackjack-allure [doublebubblebingo]',
	'play-stl-blackjack-allure [jackpotjoy]',
	'play-stl-blackjack-allure [monopolycasino]',
	'play-stl-blackjack-allure [rainbowriches]',
	'play-stl-blackjack-allure [virgingames]',
	'play-stl-blackjack-classic-1 [ballyuk]',
	'play-stl-blackjack-classic-1 [doublebubblebingo]',
	'play-stl-blackjack-classic-1 [jackpotjoy]',
	'play-stl-blackjack-classic-1 [monopolycasino]',
	'play-stl-blackjack-classic-1 [rainbowriches]',
	'play-stl-blackjack-classic-1 [virgingames]',
	'play-stl-blackjack-classic-2 [ballyuk]',
	'play-stl-blackjack-classic-2 [doublebubblebingo]',
	'play-stl-blackjack-classic-2 [jackpotjoy]',
	'play-stl-blackjack-classic-2 [monopolycasino]',
	'play-stl-blackjack-classic-2 [rainbowriches]',
	'play-stl-blackjack-classic-2 [virgingames]',
	'play-stl-blackjack-classic-4 [ballyuk]',
	'play-stl-blackjack-classic-4 [doublebubblebingo]',
	'play-stl-blackjack-classic-4 [jackpotjoy]',
	'play-stl-blackjack-classic-4 [monopolycasino]',
	'play-stl-blackjack-classic-4 [rainbowriches]',
	'play-stl-blackjack-classic-4 [virgingames]',
	'play-stl-blackjack-classic-5 [ballyuk]',
	'play-stl-blackjack-classic-5 [doublebubblebingo]',
	'play-stl-blackjack-classic-5 [jackpotjoy]',
	'play-stl-blackjack-classic-5 [monopolycasino]',
	'play-stl-blackjack-classic-5 [rainbowriches]',
	'play-stl-blackjack-classic-5 [virgingames]',
	'play-stl-blackjack-prestige [ballyuk]',
	'play-stl-blackjack-prestige [doublebubblebingo]',
	'play-stl-blackjack-prestige [jackpotjoy]',
	'play-stl-blackjack-prestige [monopolycasino]',
	'play-stl-blackjack-prestige [rainbowriches]',
	'play-stl-blackjack-prestige [virgingames]',
	'play-stl-blackjack-vip-crystal [ballyuk]',
	'play-stl-blackjack-vip-crystal [doublebubblebingo]',
	'play-stl-blackjack-vip-crystal [jackpotjoy]',
	'play-stl-blackjack-vip-crystal [monopolycasino]',
	'play-stl-blackjack-vip-crystal [rainbowriches]',
	'play-stl-blackjack-vip-crystal [virgingames]',
	'play-stl-book-of-adventure-super-stake [ballyuk]',
	'play-stl-book-of-adventure-super-stake [doublebubblebingo]',
	'play-stl-book-of-adventure-super-stake [jackpotjoy]',
	'play-stl-book-of-adventure-super-stake [monopolycasino]',
	'play-stl-book-of-adventure-super-stake [rainbowriches]',
	'play-stl-book-of-adventure-super-stake [virgingames]',
	'play-stl-book-of-cleopatra-2 [ballyuk]',
	'play-stl-book-of-cleopatra-2 [doublebubblebingo]',
	'play-stl-book-of-cleopatra-2 [jackpotjoy]',
	'play-stl-book-of-cleopatra-2 [monopolycasino]',
	'play-stl-book-of-cleopatra-2 [rainbowriches]',
	'play-stl-book-of-cleopatra-2 [virgingames]',
	'play-stl-burgundy-auto-roulette [ballyuk]',
	'play-stl-burgundy-auto-roulette [doublebubblebingo]',
	'play-stl-burgundy-auto-roulette [jackpotjoy]',
	'play-stl-burgundy-auto-roulette [monopolycasino]',
	'play-stl-burgundy-auto-roulette [rainbowriches]',
	'play-stl-burgundy-auto-roulette [virgingames]',
	'play-stl-burgundy-auto-roulette-classic [ballyuk]',
	'play-stl-burgundy-auto-roulette-classic [doublebubblebingo]',
	'play-stl-burgundy-auto-roulette-classic [jackpotjoy]',
	'play-stl-burgundy-auto-roulette-classic [monopolycasino]',
	'play-stl-burgundy-auto-roulette-classic [rainbowriches]',
	'play-stl-burgundy-auto-roulette-classic [virgingames]',
	'play-stl-candyways-bonanza-2-megaways [ballyuk]',
	'play-stl-candyways-bonanza-2-megaways [doublebubblebingo]',
	'play-stl-candyways-bonanza-2-megaways [jackpotjoy]',
	'play-stl-candyways-bonanza-2-megaways [monopolycasino]',
	'play-stl-candyways-bonanza-2-megaways [rainbowriches]',
	'play-stl-candyways-bonanza-2-megaways [virgingames]',
	'play-stl-classic-auto-roulette [ballyuk]',
	'play-stl-classic-auto-roulette [doublebubblebingo]',
	'play-stl-classic-auto-roulette [jackpotjoy]',
	'play-stl-classic-auto-roulette [monopolycasino]',
	'play-stl-classic-auto-roulette [rainbowriches]',
	'play-stl-classic-auto-roulette [virgingames]',
	'play-stl-erics-big-catch [ballyuk]',
	'play-stl-erics-big-catch [doublebubblebingo]',
	'play-stl-erics-big-catch [jackpotjoy]',
	'play-stl-erics-big-catch [monopolycasino]',
	'play-stl-erics-big-catch [rainbowriches]',
	'play-stl-erics-big-catch [virgingames]',
	'play-stl-glam-roulette [ballyuk]',
	'play-stl-glam-roulette [doublebubblebingo]',
	'play-stl-glam-roulette [jackpotjoy]',
	'play-stl-glam-roulette [monopolycasino]',
	'play-stl-glam-roulette [rainbowriches]',
	'play-stl-glam-roulette [virgingames]',
	'play-stl-jackpotjoy-roulette [jackpotjoy]',
	'play-stl-money-track [ballyuk]',
	'play-stl-money-track [doublebubblebingo]',
	'play-stl-money-track [jackpotjoy]',
	'play-stl-money-track [monopolycasino]',
	'play-stl-money-track [rainbowriches]',
	'play-stl-money-track [virgingames]',
	'play-stl-money-track-2 [ballyuk]',
	'play-stl-money-track-2 [doublebubblebingo]',
	'play-stl-money-track-2 [jackpotjoy]',
	'play-stl-money-track-2 [monopolycasino]',
	'play-stl-money-track-2 [rainbowriches]',
	'play-stl-money-track-2 [virgingames]',
	'play-stl-runner-runner-roulette-5000x[ballyuk]',
	'play-stl-runner-runner-roulette-5000x[doublebubblebingo]',
	'play-stl-runner-runner-roulette-5000x[jackpotjoy]',
	'play-stl-runner-runner-roulette-5000x[monopolycasino]',
	'play-stl-runner-runner-roulette-5000x[rainbowriches]',
	'play-stl-runner-runner-roulette-5000x[virgingames]',
	'play-stl-runner-runner-roulette-500x[doublebubblebingo]',
	'play-stl-runner-runner-roulette-500x[jackpotjoy]',
	'play-stl-runner-runner-roulette-500x[monopolycasino]',
	'play-stl-runner-runner-roulette-500x[rainbowriches]',
	'play-stl-runner-runner-roulette-500x[virgingames]',
	'play-stl-signature-roulette [ballyuk]',
	'play-stl-signature-roulette [doublebubblebingo]',
	'play-stl-signature-roulette [jackpotjoy]',
	'play-stl-signature-roulette [monopolycasino]',
	'play-stl-signature-roulette [rainbowriches]',
	'play-stl-signature-roulette [virgingames]',
	'play-stl-speed-baccarat-1 [ballyuk]',
	'play-stl-speed-baccarat-1 [doublebubblebingo]',
	'play-stl-speed-baccarat-1 [jackpotjoy]',
	'play-stl-speed-baccarat-1 [monopolycasino]',
	'play-stl-speed-baccarat-1 [rainbowriches]',
	'play-stl-speed-baccarat-1 [virgingames]',
	'play-stl-sport-auto-roulette [ballyuk]',
	'play-stl-sport-auto-roulette [doublebubblebingo]',
	'play-stl-sport-auto-roulette [jackpotjoy]',
	'play-stl-sport-auto-roulette [monopolycasino]',
	'play-stl-sport-auto-roulette [rainbowriches]',
	'play-stl-sport-auto-roulette [virgingames]',
	'play-stl-super-stake-blackjack [ballyuk]',
	'play-stl-super-stake-blackjack [doublebubblebingo]',
	'play-stl-super-stake-blackjack [jackpotjoy]',
	'play-stl-super-stake-blackjack [monopolycasino]',
	'play-stl-super-stake-blackjack [rainbowriches]',
	'play-stl-super-stake-blackjack [virgingames]',
	'play-stl-super-stake-roulette [ballyuk]',
	'play-stl-super-stake-roulette [doublebubblebingo]',
	'play-stl-super-stake-roulette [jackpotjoy]',
	'play-stl-super-stake-roulette [monopolycasino]',
	'play-stl-super-stake-roulette [rainbowriches]',
	'play-stl-super-stake-roulette [virgingames]',
	'play-stl-vip-classic-auto-roulette [ballyuk] ',
	'play-stl-vip-classic-auto-roulette [doublebubblebingo] ',
	'play-stl-vip-classic-auto-roulette [jackpotjoy] ',
	'play-stl-vip-classic-auto-roulette [monopolycasino] ',
	'play-stl-vip-classic-auto-roulette [rainbowriches] ',
	'play-stl-vip-classic-auto-roulette [virgingames] ',
	'play-stl-virgin-roulette [virgingames]',
	'play-stl-wild-wild-bass [ballyuk]',
	'play-stl-wild-wild-bass [doublebubblebingo]',
	'play-stl-wild-wild-bass [jackpotjoy]',
	'play-stl-wild-wild-bass [monopolycasino]',
	'play-stl-wild-wild-bass [rainbowriches]',
	'play-stl-wild-wild-bass [virgingames]',
	'play-stl-wild-wild-bass-2 [ballyuk]',
	'play-stl-wild-wild-bass-2 [doublebubblebingo]',
	'play-stl-wild-wild-bass-2 [jackpotjoy]',
	'play-stl-wild-wild-bass-2 [monopolycasino]',
	'play-stl-wild-wild-bass-2 [rainbowriches]',
	'play-stl-wild-wild-bass-2 [virgingames]'
];

module.exports = {
	includedGames
}
