const includedGames = [
	'STL_BLACKJACK_ALLURE',
	'STL_BLACKJACK_CLASSIC_1',
	'STL_BLACKJACK_CLASSIC_2',
	'STL_BLACKJACK_CLASSIC_4',
	'STL_BLACKJACK_CLASSIC_5',
	'STL_BLACKJACK_PRESTIGE',
	'STL_BLACKJACK_VIP_CRYSTAL',
	'STL_BOOK_OF_ADVENTURE_SUPER_STAKE',
	'STL_BOOK_OF_CLEOPATRA_2',
	'STL_BRANDED_ROULETTE',
	'STL_BURGUNDY_AUTO_ROULETTE',
	'STL_BURGUNDY_AUTO_ROULETTE_CLASSIC',
	'STL_CANDYWAYS_BONANZA_2_MEGAWAYS',
	'STL_CLASSIC_AUTO_ROULETTE',
	'STL_ERICS_BIG_CATCH',
	'STL_GLAM_ROULETTE',
	'STL_MONEY_TRACK',
	'STL_MONEY_TRACK_2',
	'STL_RUNNER_RUNNER_ROULETTE_5000X',
	'STL_RUNNER_RUNNER_ROULETTE_500X',
	'STL_SIGNATURE_ROULETTE',
	'STL_SPEED_BACCARAT_1',
	'STL_SPORT_AUTO_ROULETTE',
	'STL_SUPER_STAKE_BLACKJACK',
	'STL_SUPER_STAKE_ROULETTE',
	'STL_VIP_CLASSIC_AUTO_ROULETTE',
	'STL_WILD_WILD_BASS',
	'STL_WILD_WILD_BASS_2'
];

module.exports = {
	includedGames
}
