import { writeFile, readdir, readFile } from "node:fs/promises";
import { join } from "node:path";

// Script used to create the metadata.json file from participants.json and teams.csv generated by the Assets generation scripts
// There is no need to run this script again as the metadata.json file is already created

const metadataDictionary = {};

// Get all subdirectories in the data folder
const dataPath = "./data";
const entries = await readdir(dataPath, { withFileTypes: true });
const subdirectories = entries
  .filter(entry => entry.isDirectory())
  .map(entry => entry.name);

console.log(`Processing ${subdirectories.length} competitions:`, subdirectories);

// Process each subdirectory
for (const subdirectory of subdirectories) {
  console.log(`Processing ${subdirectory}...`);
  
  try {
    const participantsData = await readFile(
      join(dataPath, subdirectory, "participants.json"),
      "utf-8"
    );
    const teamsData = await readFile(
      join(dataPath, subdirectory, "teams.csv"), 
      "utf-8"
    );

    const participants = JSON.parse(participantsData);

    const lines = teamsData
      .toString()
      .split("\n")
      .slice(1)
      .filter((l) => l.length);

    for (let line of lines) {
      const [name, , , , , , template, black, white, , key] = line.split("\t");

      // Find participant that contains the key
      const participantEntry = Object.entries(participants).find(([_, participant]) => 
        participant.key && participant.key.includes(key)
      );

      if (!participantEntry) {
        console.warn(`No participant found with key: ${key} for ${name} in ${subdirectory}`);
        continue;
      }

      const metadataKey = participantEntry[1].logo;
      if (!metadataKey) {
        console.warn(`No logo found for participant with key: ${key} (${name}) in ${subdirectory}`);
        continue;
      }

      metadataDictionary[metadataKey] = {
        black,
        white,
        template,
      };
    }
    
    console.log(`✓ Completed ${subdirectory}`);
  } catch (error) {
    console.error(`Error processing ${subdirectory}:`, error.message);
  }
}

writeFile("./data/metadata.json", JSON.stringify(metadataDictionary));
