import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import csv from 'csv-parser';


const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// participants.json generated by a query to Contentful
const jsonFilePath = path.join(__dirname, 'participants.json');
// csv is generated by matchday_participants.js script
const csvFilePath = path.join(__dirname, 'teams.csv')

async function main() {
  const participants = JSON.parse(await fs.promises.readFile(jsonFilePath, 'utf8'));

  const csvData = new Map();

  await new Promise((resolve, reject) => {
    fs.createReadStream(csvFilePath)
      .pipe(csv())
      .on('data', (row) => {
        csvData.set(row.path, row.key);
      })
      .on('end', resolve)
      .on('error', reject);
  });
  let updatedCount = 0;
  participants.forEach(participant => {

    // edit here if needed to match by name instead of participantPath
    const matchBy = participant.participantPath

    if (csvData.has(matchBy)) {
      const newId = csvData.get(matchBy);
      // if participant doesn't have keys yet, create the array
      if (!participant.id) {
        participant.id = [newId];
      }
      // insert key if it doesn't already exist
      else if (Array.isArray(participant.id)) {
        if (!participant.id.includes(newId)) {
          participant.id.push(newId);
        }
      }
      updatedCount++;
    }
  });

  await fs.promises.writeFile(jsonFilePath, JSON.stringify(participants, null, 2));

  console.log(`Number of participants updated: ${updatedCount}`);
}

main().catch(console.error);
