import { MigrationFunction } from 'contentful-migration';

export = ((migration) => {
    const cashierGameConfig = migration.editContentType('cashierGameConfig');

    cashierGameConfig.editField('gameProvider').validations([
        {
            in: [
                'AGS',
                'AINSWORTH',
                'AMAYA',
                'BETWORKS',
                'BLUEPRINT',
                'COLOSSUS',
                'DGC',
                'EVERI',
                'EVOLUTION',
                'EYECON',
                'GAMESYS',
                'GAMESYSGAMES',
                'GAMINGREALMS',
                'GAMOMAT',
                'GAN',
                'GOLDENHERO',
                'GREENTUBE',
                'HIGH5GAMES',
                'HUNGRYBEAR',
                'IGT',
                'INCREDIBLETECHNOLOGIES',
                'INSPIRED',
                'KONAMI',
                'METRIC',
                'MICROGAMING',
                'NETENT',
                'NOVOMATIC',
                'ORYX',
                'PLAYNGO',
                'PLAYSON',
                'PLAYTECH',
                'PLAYZIDO',
                'PRAGMATICPLAY',
                'PUSHGAMING',
                'RAW',
                'REALISTICGAMES',
                'REDTIGER',
                'RELAXGAMING',
                'ROGUE',
                'ROXOR',
                'SAPPHIRE',
                'SDK',
                'SPIN',
                'SGDIGITAL',
                'THUNDERKICK',
                'WHITEHAT',
                'WMS',
                '1X2NETWORK',
                '3RADICAL',
            ],
        },
    ]);
}) as MigrationFunction;
